name: Push Deployment to production - main

on:
  push:
    branches:
      - main
    paths:
      - "force-app/**"

jobs:
  deploy-to-production:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Checkout source code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Salesforce CLI
        run: npm install --global @salesforce/cli

      - name: Install sfdx git delta plugin
        run: echo y | sf plugins install sfdx-git-delta

      - name: Generate delta package from previous commit
        run: |
          FROM_COMMIT=$(jq -r .before "$GITHUB_EVENT_PATH")
          echo "Using delta from $FROM_COMMIT to HEAD"

          mkdir changed-sources
          sf sgd source delta \
            --to "HEAD" \
            --from "$FROM_COMMIT" \
            --output-dir changed-sources/ \
            --generate-delta \
            --source-dir force-app/

      - name: List delta package contents
        run: ls -R changed-sources/

      - name: Authenticate to Salesforce
        run: |
          echo "${{ secrets.SF_AUTH_URL }}" | sf org login sfdx-url --sfdx-url-stdin -d -s

      - name: Deploy delta package - run all tests
        run: |
          sf project deploy start \
            --manifest "changed-sources/package/package.xml" \
            --test-level RunLocalTests \
            --pre-destructive-changes "changed-sources/destructiveChanges/package.xml" \
            --ignore-warnings \
            --wait 60 \
            --verbose
